import { Montserrat } from "next/font/google";
import "../globals.css";
import { AppSidebar } from "../components/almacenistacomponents/dashboard";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["200", "400", "500", "700"],
});

export const metadata = {
  title: "+IDEAS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${montserrat.className} antialiased `}>
        <SidebarProvider defaultOpen={false}>
          <AppSidebar />
          <main>
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
